### ISSUE TITLE
cf_malloc(FALSE) uses TOS Malloc / Mxalloc for no good reason

### ISSUE THREAD

**Issue by mikrosk** [freemint/cflib#5]
I thought that `cf_malloc`is used in rare cases where TOS M(x)alloc is explicitly needed, like `malloc_global`. However it seems that e.g. USERBLKs are using it for no particular reason creating havoc for simpler memory allocators as described by @czietz [here](https://sourceforge.net/p/emutos/mailman/emutos-devel/thread/f7beae0f-73ea-5722-a6f4-46e9926a9cfc%40gmx.net/#msg37770628) and [here](https://sourceforge.net/p/emutos/mailman/emutos-devel/thread/ec9302e1-c9df-f528-8c3e-f47d1226819c%40gmx.net/#msg37770656).

Perhaps in the earlier times dependency on mintlib (or libc in general) wasn't desired but nowadays it doesn't matter.

Another good point would be why the hell 8 bytes need separate dynamic allocation.

**Comment by th-otto** [comment]
I did a grep through the sources, and added a fix. cf_malloc is only defined in intern.h so should be local to cflib and not be exported, so i hope the fix can be done in cflib (unless some brain-damaged app imports that function illegaly).

I also changed fix_dial to allocate all needed USERBLKs in one go instead of allocating each structure separately. This could maybe further improved to provide an additional function that fixes *all* objects of a resource in one go, instead of doing it per tree, but this would require also changes to applications that use the function currently (found only QED and toswin2 so far, are there any others?)

Tested only with QED so far, and found no issues.

**Comment by mikrosk** [comment]
Oh nice, many thanks for that. I've rerun all the jobs (qed, toswin2, bootable freemint packages), @czietz as you have a working setup with the bug present, can you verify that downloading the latest qed fixes the problem in EmuTOS?

> found only QED and toswin2 so far, are there any others?

If you ask generally, then I know of HD Driver and ... my mxPlay. :)

**Comment by czietz** [comment]
Using the Aranym image with which Philippe reported the issue in the
first place (on emutos-devel), I can confirm: The latest snapshot of QED
does not complain anymore about failing to allocate memory. Furthermore,
with Hatari I can see that the amount of Malloc calls to the OS has been
greatly reduced.

Thank you!

PS: I did not use the new QED snapshot extensively, though, to test for
any side-effects.

**Comment by mikrosk** [comment]
Awesome, thanks to both of you.
